---
- name: Install Linux Kernel 5.10.0-1019
  apt:
    name: linux-image-5.10.0-1019-oem
    state: present
  become: yes

- name: Install base packages
  apt:
    pkg:
      - wget
      - git
      - bcc
      - bin86
      - gawk
      - bridge-utils
      - iproute2
      - libcurl4-openssl-dev
      - bzip2
      - libpci-dev
      - build-essential
      - make
      - gcc
      - clang
      - libc6-dev
      - linux-libc-dev
      - zlib1g-dev
      - libncurses5-dev
      - patch
      - libvncserver-dev
      - libssl-dev
      - libsdl-dev
      - iasl
      - libbz2-dev
      - e2fslibs-dev
      - git-core
      - uuid-dev
      - ocaml
      - libx11-dev
      - bison
      - flex
      - ocaml-findlib
      - xz-utils
      - gettext
      - libyajl-dev
      - libpixman-1-dev
      - libaio-dev
      - libfdt-dev
      - cabextract
      - libglib2.0-dev
      - autoconf
      - automake
      - libtool
      - libjson-c-dev
      - libfuse-dev
      - liblzma-dev
      - autoconf-archive
      - kpartx
      - python3-dev
      - python3-pip
      - python3-setuptools
      - golang
      - python-dev
      - libsystemd-dev
      - nasm
      - python3-pefile
    state: present
  become: yes
  tags:
    - base

- name: Install construct from Pypi (which is too old in debian sources)
  pip:
    name: construct >=2.10.67
    executable: pip3
