# Prepare environment for Drakvuf
- name: Remove old drakvuf repo
  file:
    path: "{{ build_dir }}"
    state: absent
  become: yes

- name: Change owner of {{ build_dir }} directory
  become: yes
  file:
    path: "{{ build_dir }}/"
    state: directory
    owner: "{{ drakvuf_user }}"
    group: "{{ drakvuf_user }}"
    recurse: true

# Get drakvuf's code
- name: Clone drakvuf repo
  git:
    repo: "{{ drakvuf_repo }}"
    dest: "{{ build_dir }}"
    recursive: yes
    update: yes
    version: master
  become: yes # needed for write permissions on build dir
  become_user: "{{ drakvuf_user }}"
