* ansible-drakvuf

** :exclamation: Disclaimer
This repository is work in progress, if you encounter any bugs or other problems, please report them.

** Description
This repository provides an Ansible playbook to deploy the black-box binary analysis system [[https://github.com/tklengyel/drakvuf][DRAKVUF©]] on a host, which is based on Ubuntu 20.04 from scratch. (Debian Bullseye should work also, but has not been tested yet.)

The role ~drakvuf-dev~ aims at installing a basic development environment for working on DRAKVUF©. It follows the guide at [[https://drakvuf.com/][drakvuf.com]] and automates the commands mentioned there.

** Usage
1. Insert the IP of your target machine to the inventory ~./inventory/hosts~ and make sure, that it is accessible via passwordless SSH.
2. Edit the variables inside ~./roles/drakvuf-dev/defaults/main.yml~ to match your environment, if needed. 
3. Use ~ansible-playbook~ to run the setup process 
    #+begin_src bash
    ansible-playbook -i inventory/hosts playbooks/playbook.yml --ask-become-pass -vvv
    #+end_src

Afterwards you have to manual create your domU machine and create the corresponding Intermediate Symbol File (ISF), which is needed by libvmi and DRAKVUF© to perform introspection. 

** References
[1] https://drakvuf.com/

[2] https://pub.nethence.com/security/drakvuf
