# Base vars
distribution: focal
# User, which uses drakvuf
drakvuf_user: user01
# Drakvufs directory
build_dir: /usr/local/src/drakvuf
# Netplan config to insert the bridge to
netplan_file: 00-installer-config.yaml
# NIC to bridge
nic: eno1
# Name of the bridge to create
br_name: xenbr0
